# Generated by Django 3.0.8 on 2021-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servies',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('s_image', models.ImageField(upload_to='artist/images')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
