# Generated by Django 3.0.8 on 2021-03-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servies',
            new_name='Services',
        ),
    ]
