# Generated by Django 3.0.8 on 2021-03-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=40)),
                ('c_email', models.EmailField(max_length=70)),
                ('c_phone', models.IntegerField()),
                ('c_msg', models.CharField(max_length=255)),
            ],
        ),
    ]
