# Generated by Django 3.0.8 on 2021-03-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='a_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='art',
            name='a_price',
            field=models.IntegerField(),
        ),
    ]
